if(EXISTS "C:/Users/Rick/Documents/Applied Software Design/vs_build/unit_tests_tests-b858cb2.cmake")
  include("C:/Users/Rick/Documents/Applied Software Design/vs_build/unit_tests_tests-b858cb2.cmake")
else()
  add_test(unit_tests_NOT_BUILT-b858cb2 unit_tests_NOT_BUILT-b858cb2)
endif()
