add_test( [==[test token construction]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[test token construction]==])
set_tests_properties( [==[test token construction]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[test comparison operators]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[test comparison operators]==])
set_tests_properties( [==[test comparison operators]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[test << operator]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[test << operator]==])
set_tests_properties( [==[test << operator]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Test empty stream]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Test empty stream]==])
set_tests_properties( [==[Test empty stream]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[test one string]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[test one string]==])
set_tests_properties( [==[test one string]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[test simple strings, one per line]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[test simple strings\, one per line]==])
set_tests_properties( [==[test simple strings, one per line]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Test comments]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Test comments]==])
set_tests_properties( [==[Test comments]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[test fact lexing]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[test fact lexing]==])
set_tests_properties( [==[test fact lexing]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Test rules]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Test rules]==])
set_tests_properties( [==[Test rules]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Test compound lexing]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Test compound lexing]==])
set_tests_properties( [==[Test compound lexing]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Anonymous test case 1]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Anonymous test case 1]==])
set_tests_properties( [==[Anonymous test case 1]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Manual Tests Expression Tree]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Manual Tests Expression Tree]==])
set_tests_properties( [==[Manual Tests Expression Tree]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Correct Tree formation]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Correct Tree formation]==])
set_tests_properties( [==[Correct Tree formation]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Error Testing]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Error Testing]==])
set_tests_properties( [==[Error Testing]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Manual Tests]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Manual Tests]==])
set_tests_properties( [==[Manual Tests]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Parse Query Tests]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Parse Query Tests]==])
set_tests_properties( [==[Parse Query Tests]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Parse KnowledgeBase]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Parse KnowledgeBase]==])
set_tests_properties( [==[Parse KnowledgeBase]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Ask tests]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Ask tests]==])
set_tests_properties( [==[Ask tests]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( Unionize [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] Unionize)
set_tests_properties( Unionize PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Anonymous test case 2]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Anonymous test case 2]==])
set_tests_properties( [==[Anonymous test case 2]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Anonymous test case 3]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Anonymous test case 3]==])
set_tests_properties( [==[Anonymous test case 3]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( APPLY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] APPLY)
set_tests_properties( APPLY PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
add_test( [==[Test unification with expression list failure]==] [==[C:/Users/Rick/Documents/Applied Software Design/vs_build/Debug/unit_tests.exe]==] [==[Test unification with expression list failure]==])
set_tests_properties( [==[Test unification with expression list failure]==] PROPERTIES WORKING_DIRECTORY [==[C:/Users/Rick/Documents/Applied Software Design/vs_build]==])
set( unit_tests_TESTS [==[test token construction]==] [==[test comparison operators]==] [==[test << operator]==] [==[Test empty stream]==] [==[test one string]==] [==[test simple strings, one per line]==] [==[Test comments]==] [==[test fact lexing]==] [==[Test rules]==] [==[Test compound lexing]==] [==[Anonymous test case 1]==] [==[Manual Tests Expression Tree]==] [==[Correct Tree formation]==] [==[Error Testing]==] [==[Manual Tests]==] [==[Parse Query Tests]==] [==[Parse KnowledgeBase]==] [==[Ask tests]==] Unionize [==[Anonymous test case 2]==] [==[Anonymous test case 3]==] APPLY [==[Test unification with expression list failure]==])
